/* soapBasicHttpBinding_USCOREICouponServiceProxy.h
   Generated by gSOAP 2.8.2 from Init.h
   Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

#ifndef soapBasicHttpBinding_USCOREICouponServiceProxy_H
#define soapBasicHttpBinding_USCOREICouponServiceProxy_H
#include "soapH.h"
class BasicHttpBinding_USCOREICouponService
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'BasicHttpBinding_USCOREICouponService' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	BasicHttpBinding_USCOREICouponService()
	{ soap = soap_new(); endpoint = "http://116.12.134.130:21012/"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns4", "http://schemas.datacontract.org/2004/07/CouponService", NULL, NULL},
	{"ns3", "http://schemas.microsoft.com/2003/10/Serialization/", NULL, NULL},
	{"ns1", "http://tempuri.org/", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~BasicHttpBinding_USCOREICouponService() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'ScreenCoupon' of service 'BasicHttpBinding_USCOREICouponService' and return error code (or SOAP_OK)
	virtual int __ns1__ScreenCoupon(_ns1__ScreenCoupon *ns1__ScreenCoupon, _ns1__ScreenCouponResponse *ns1__ScreenCouponResponse) { return soap ? soap_call___ns1__ScreenCoupon(soap, endpoint, NULL, ns1__ScreenCoupon, ns1__ScreenCouponResponse) : SOAP_EOM; };
	/// Invoke 'UpdateCouponStatus' of service 'BasicHttpBinding_USCOREICouponService' and return error code (or SOAP_OK)
	virtual int __ns1__UpdateCouponStatus(_ns1__UpdateCouponStatus *ns1__UpdateCouponStatus, _ns1__UpdateCouponStatusResponse *ns1__UpdateCouponStatusResponse) { return soap ? soap_call___ns1__UpdateCouponStatus(soap, endpoint, NULL, ns1__UpdateCouponStatus, ns1__UpdateCouponStatusResponse) : SOAP_EOM; };
};
#endif
