/* soapClient.cpp
   Generated by gSOAP 2.8.2 from Init.h
   Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif

#include "Stdafx.h"
#include "soapH.h"

#ifdef _SG

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.8.2 2011-05-18 07:07:58 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ScreenCoupon(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__ScreenCoupon *ns1__ScreenCoupon, _ns1__ScreenCouponResponse *ns1__ScreenCouponResponse)
{	struct __ns1__ScreenCoupon soap_tmp___ns1__ScreenCoupon;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.1.240:21012/";
	if (!soap_action)
		soap_action = "http://tempuri.org/ICouponService/ScreenCoupon";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__ScreenCoupon.ns1__ScreenCoupon = ns1__ScreenCoupon;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__ScreenCoupon(soap, &soap_tmp___ns1__ScreenCoupon);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__ScreenCoupon(soap, &soap_tmp___ns1__ScreenCoupon, "-ns1:ScreenCoupon", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__ScreenCoupon(soap, &soap_tmp___ns1__ScreenCoupon, "-ns1:ScreenCoupon", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__ScreenCouponResponse)
		return soap_closesock(soap);
	ns1__ScreenCouponResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__ScreenCouponResponse->soap_get(soap, "ns1:ScreenCouponResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__UpdateCouponStatus(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__UpdateCouponStatus *ns1__UpdateCouponStatus, _ns1__UpdateCouponStatusResponse *ns1__UpdateCouponStatusResponse)
{	struct __ns1__UpdateCouponStatus soap_tmp___ns1__UpdateCouponStatus;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.1.240:21012/";
	if (!soap_action)
		soap_action = "http://tempuri.org/ICouponService/UpdateCouponStatus";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__UpdateCouponStatus.ns1__UpdateCouponStatus = ns1__UpdateCouponStatus;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__UpdateCouponStatus(soap, &soap_tmp___ns1__UpdateCouponStatus);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__UpdateCouponStatus(soap, &soap_tmp___ns1__UpdateCouponStatus, "-ns1:UpdateCouponStatus", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__UpdateCouponStatus(soap, &soap_tmp___ns1__UpdateCouponStatus, "-ns1:UpdateCouponStatus", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__UpdateCouponStatusResponse)
		return soap_closesock(soap);
	ns1__UpdateCouponStatusResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__UpdateCouponStatusResponse->soap_get(soap, "ns1:UpdateCouponStatusResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

#endif		//#ifdef _SG
/* End of soapClient.cpp */
