/* soapBasicHttpBinding_USCOREIGameAuthenticationProxy.h
   Generated by gSOAP 2.8.2 from Init.h
   Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

#if defined (_SG)

#ifndef soapBasicHttpBinding_USCOREIGameAuthenticationProxy_H
#define soapBasicHttpBinding_USCOREIGameAuthenticationProxy_H

#if defined(PRE_MOD_SG_WITH_MACADDR)
#include "./MacAddrVer/soapH.h"
#else		//#if defined(PRE_MOD_SG_WITH_MACADDR)
#include "soapH.h"
#endif		//#if defined(PRE_MOD_SG_WITH_MACADDR)

class BasicHttpBinding_USCOREIGameAuthentication
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'BasicHttpBinding_USCOREIGameAuthentication' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	BasicHttpBinding_USCOREIGameAuthentication()
	{ 
		soap = soap_new(); endpoint = "http://192.168.1.240:22011/"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
		{
			{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
			{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
			{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
			{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
			{"ns4", "http://schemas.microsoft.com/2003/10/Serialization/", NULL, NULL},
			{"ns5", "http://tempuri.org/BasicHttpBinding_IGameAuthentication", NULL, NULL},
			{"ns3", "http://ac.cherrycredits.com/", NULL, NULL},
			{"ns6", "http://tempuri.org/NetTcpBinding_IGameAuthentication", NULL, NULL},
			{NULL, NULL, NULL, NULL}
		};
		soap->namespaces = namespaces; }
	};
	/// Destructor frees deserialized data and soap engine context
	virtual ~BasicHttpBinding_USCOREIGameAuthentication() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'Authenticate' of service 'BasicHttpBinding_USCOREIGameAuthentication' and return error code (or SOAP_OK)
	virtual int __ns5__Authenticate(_ns3__Authenticate *ns3__Authenticate, _ns3__AuthenticateResponse *ns3__AuthenticateResponse) { return soap ? soap_call___ns5__Authenticate(soap, endpoint, NULL, ns3__Authenticate, ns3__AuthenticateResponse) : SOAP_EOM; };
	/// Invoke 'CreateAccount' of service 'BasicHttpBinding_USCOREIGameAuthentication' and return error code (or SOAP_OK)
	virtual int __ns5__CreateAccount(_ns3__CreateAccount *ns3__CreateAccount, _ns3__CreateAccountResponse *ns3__CreateAccountResponse) { return soap ? soap_call___ns5__CreateAccount(soap, endpoint, NULL, ns3__CreateAccount, ns3__CreateAccountResponse) : SOAP_EOM; };
};
#endif

#endif