#pragma once

#ifdef PRE_MOD_BROWSER

enum eBrowserType
{
	eBT_GENERAL,
	eBT_NPCBROWSER,
};

enum eBrowserError
{
	eERRBROWSER_NONE,
	eERRBROWSER_CANT_OPEN_GENERAL = 20000,
	eERRBROWSER_CANT_OPEN_D3D,
	eERRBROWSER_CANT_OPEN_COCREATE_FAIL,
	eERRBROWSER_CANT_OPEN_CHARGEBROWSER_ATTACH_IE_EVENT_FAIL,
	eERRBROWSER_SIZE_FAIL,
	eERRBROWSER_NAVIGATE_FAIL,
	eERRBROWSER_ALREADY_OPENED,
	eERRBROWSER_CANT_OPEN_CHARGEBROWSER_TYPE_FAIL,
	eERRBROWSER_NO_URL,
};

#endif // PRE_MOD_BROWSER