#pragma once

#define UM_REFRESH_VIEW WM_USER + 1000
#define UM_REFRESH_PANE WM_USER + 1001

#define UM_ACTION_PANE_ADD WM_USER + 1002

#define UM_PROPERTY_PANE_SET_READONLY WM_USER + 1003
#define UM_PROPERTY_PANE_SET_MODIFY WM_USER + 1004

#define UM_EVENT_PANE_UPDATE_FRAME WM_USER + 1005
#define UM_EVENT_PANE_RESETCOPYCUT WM_USER + 1009

#define UM_TREEEX_UPDATECHECK WM_USER + 1007

#define UM_LIGHT_PANE_ADD WM_USER + 1008
